### ISSUE TITLE
在集群之外如何访问kafka集群

### ISSUE THREAD

**Issue by qknavy** [cuishuaigit/k8s-kafka#4]
kafka集群是顺利搭建起来了，但是在k8s集群之外访问这个kafka集群就访问不到了。比如我的开发环境k8s搭建的kafka，我本地电脑运行代码的时候需要去连，最终会报一个k8s集群自动映射的域名出来说找不到

**Comment by cuishuaigit** [comment]
本地去连接k8s集群内部的服务，如果是测试可以考虑使用nodeport或ingress的tcp代理

**Comment by cuishuaigit** [comment]
有问题再打开
